---
title: "Новый документ"
author: "И. О. Фамилия"
format: html
lang: ru

knitr: 
  opts_chunk: 
    collapse: true

# обязательно!
# иначе графики будут дублироваться в отчетах
# execute:
#   cache: false

params:
  species: Gentoo
---

## Новый параграф

Отчет для `r params$species`.

```{r}
palmerpenguins::penguins |>
  dplyr::filter(species == params$species) |>
  nrow()
```

```{r}
#| message: false
#| warning: false
#| echo: false

data_to_plot <- palmerpenguins::penguins |>
  na.omit() |>
  dplyr::filter(species == params$species)
```

```{r}
#| message: false
#| warning: false
#| echo: false
#| cache-rebuild: true

data_to_plot |>
  ggplot2::ggplot(ggplot2::aes(x = body_mass_g,
                      y = flipper_length_mm)) +
  ggplot2::geom_point(data = palmerpenguins::penguins |>
               na.omit(),
             size = 4, color = "white", 
             pch = 21, 
             alpha = 0.8,
             fill = "grey") +
  ggplot2::geom_point(size = 4, color = "white", 
             pch = 21, 
             alpha = 0.8,
             fill = "steelblue") +
  ggplot2::theme_minimal()
```